/*
 * @file Receiver.c
 * Module Interface for Module Receiver
 * This file can be considered a template with the operation stubs
 * auto generated by the ECOA toolset and filled in by the module
 * developer.
 */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>

/* Include module interface header */
#include "Receiver.h"

static const char* RECEIVER = "Receiver: ";

void Receiver_log_info(Receiver__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, RECEIVER, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(RECEIVER, ECOA__LOG_MAXSIZE), ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    Receiver_container__log_info(context, log);
}

/* Event operation handlers */
void 
Receiver__myEvent__received (
  Receiver__context* context
  , 
  extra_types__T_Int_Type parameter
 )
{
  Receiver_log_info(context, "parameter : %d", parameter);
}

void 
Receiver__tick__received (
  Receiver__context* context
 )
{
  Receiver_log_info(context, "Tick received");
}

Receiver__myData__updated (
  Receiver__context* context
)
{
    Receiver_log_info(context, "Data updated");
}

/* Request-Response operation handlers */

/* Lifecycle operation handlers */

void Receiver__INITIALIZE__received(Receiver__context* context)
{
  Receiver_log_info(context, "Receiver initialized!");
}

void Receiver__START__received(Receiver_context* context)
{
  Receiver_log_info(context, "Receiver started!");
}

void Receiver__STOP__received(Receiver_context* context)
{
  Receiver_log_info(context, "Receiver stopped!");
}

void Receiver__SHUTDOWN__received(Receiver_context* context)
{
  Receiver_log_info(context, "Receiver shutdown!");
}


 