/*
 * @file Receiver.c
 * Module Interface for Module Receiver
 * This file can be considered a template with the operation stubs
 * auto generated by the ECOA toolset and filled in by the module
 * developer.
 */

/* Include module interface header */
#include "Receiver.h"
#include <stdio.h>

/* Event operation handlers */
void 
Receiver__msg__received (
  Receiver__context* context
  , 
  const TestLib__msg *msg
 )
{
  ECOA__log log;
  log.current_size = sprintf(log.data, "receiving message with %d elements", msg->N);
  Receiver_container__log_info (context, log);
  int error = 0;
  for (ECOA__uint32 i=0; i<msg->N; i++) {
    if (msg->tab.data[i] != (SARC_uint8) i) error++;
  }
  log.current_size = sprintf(log.data, "%d errors detected in data", error);
  Receiver_container__log_info (context, log);
}



/* Request-Response operation handlers */

/* Lifecycle operation handlers */

void Receiver__INITIALIZE__received(Receiver__context* context)
{
  /* TODO: to be implemented */
}

void Receiver__START__received(Receiver_context* context)
{
  /* TODO: to be implemented */
}

void Receiver__STOP__received(Receiver_context* context)
{
  /* TODO: to be implemented */
}

void Receiver__SHUTDOWN__received(Receiver_context* context)
{
  /* TODO: to be implemented */
}


 