/*
 * @file Sender.c
 * Module Interface for Module Sender
 * This file can be considered a template with the operation stubs
 * auto generated by the ECOA toolset and filled in by the module
 * developer.
 */

/* Include module interface header */
#include "Sender.h"
#include <stdio.h>

void Sender__INITIALIZE__received(Sender__context* context)
{
  context->user.N = 0;
}

static void send(Sender_context* context, SARC_uint32 N)
{
  TestLib__msg msg;
  ECOA__log log;
  if (N > TestLib__tab_MAXSIZE)
    N = TestLib__tab_MAXSIZE;
  log.current_size = sprintf(log.data, "sending message with %d elements", N);
  Sender_container__log_info (context, log);
  for (ECOA__uint32 i=0; i<N; i++) {
    msg.tab.data[i] = (SARC_uint8) i;
  }
  msg.tab.current_size = N;
  msg.N = N;
  Sender_container__msg__send (context, &msg);
}

void Sender__START__received(Sender_context* context)
{
  for (int i=0; i<4; i++) {

  usleep(1000000);

  send(context, 1); 
  send(context, 10); 
  send(context, 100); 
  send(context, 1000); 
  }

  // send(context, 64000);      usleep(1000000);
  // send(context, 256000);  usleep(1000000);
  // send(context, 0);  usleep(1000000);
  // send(context, 64000);  usleep(1000000);
  // send(context, 256000);  usleep(1000000);
  // send(context, 0);  usleep(1000000);
  // send(context, 320000);  usleep(1000000);
  // send(context, 0);  usleep(1000000);

  {
    ECOA__log log;
    log.current_size = sprintf(log.data, "end of test");
    Sender_container__log_info (context, log);
  }
  exit(0);
}

void Sender__STOP__received(Sender_context* context)
{
}

void Sender__SHUTDOWN__received(Sender_context* context)
{
}


 