/*
 * @file HMI.c
 * Module Interface for Module HMI
 * This file can be considered a template with the operation stubs
 * auto generated by the ECOA toolset and filled in by the module
 * developer.
 */

/* Include module interface header */
#include "HMI.h"


/* Event operation handlers */
void 
HMI__image_in__received (
  HMI__context* context
  , 
  const image__ImageType *image
 )
{
  HMI_container__log_info(context, 
    (ECOA__log) { .data = "HMI: image_in received\n" });
}



/* Request-Response operation handlers */

/* Lifecycle operation handlers */

void HMI__INITIALIZE__received(HMI__context* context)
{
  /* TODO: to be implemented */
}

void HMI__START__received(HMI_context* context)
{
  /* TODO: to be implemented */
}

void HMI__STOP__received(HMI_context* context)
{
  /* TODO: to be implemented */
}

void HMI__SHUTDOWN__received(HMI_context* context)
{
  /* TODO: to be implemented */
}


 