/* Copyright (c) 2025 THALES -- All rights reserved */

/*
 * @file Table.c
 * Module Interface for Module Table
 * This file can be considered a template with the operation stubs
 * auto generated by the ECOA toolset and filled in by the module
 * developer.
 */

/* Include module interface header */
#include "Table.h"
#include "errno.h"
#include "stdio.h"
#include <stdlib.h>



/* Event operation handlers */

/* Request-Response operation handlers */
void 
Table__take__request_received (
  Table__context* context,  
  const ECOA__uint32 ID
  , 
  ECOA__int32 which
  , 
  ECOA__int32 who
)
{
  ECOA__boolean8 taken = 0; 
  // If free
  if( context->user.Stick[which] == FREE ) { 
    taken = ECOA__TRUE; 
    context->user.Stick[which] = who; 
  } else { 
    taken = ECOA__FALSE; 
  }
   
  Table_container__take__response_send( context, ID, taken );
}

void 
Table__surrender__request_received (
  Table__context* context,
  const ECOA__uint32 ID
  , 
  ECOA__int32 which
  , 
  ECOA__int32 who
)
{
  if( context->user.Stick[which] != who ) { 
    errno = EPERM; perror( "surrender" ); 
    fprintf( stderr, "%d is trying to surrender chopstick %d held by %d...\n", who, which, context->user.Stick[which] ); 
    exit(4); 
  } else { 
    context->user.Stick[which] = FREE; 
  } 
  Table_container__surrender__response_send( context, ID ); 
}



/* Lifecycle operation handlers */

void Table__INITIALIZE__received(Table__context* context)
{
  for (int i = 0; i < 5; i++) {
    context->user.Stick[i] = FREE;
  }
}

void Table__START__received(Table_context* context)
{
  ECOA__log msg; 
  msg.current_size = sprintf( msg.data, 
  "\n\tThe Table is laid, the chopsticks are available...\n" ); 
  Table_container__log_info(context, msg);

  Table_container__ready_handle rdyHndl;

  Table_container__ready__get_write_access( context, &rdyHndl ); 
  *(rdyHndl.data) = ECOA__TRUE; 
  Table_container__ready__publish_write_access( context, &rdyHndl );
}
void Table__STOP__received(Table_context* context)
{
  /* TODO: to be implemented */
}
void Table__SHUTDOWN__received(Table_context* context)
{
  /* TODO: to be implemented */
}


  