<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.ecoa.technology/Deployment/3.0"
  targetNamespace="http://www.ecoa.technology/Deployment/3.0"
  elementFormDefault="qualified">

  <xsd:redefine schemaLocation="../Deployment.xsd">


    <xsd:complexType name="IO_interface">
      <xsd:complexContent>
        <xsd:extension base="IO_interface">
          <xsd:sequence>
          </xsd:sequence>
          <xsd:attribute name="endianness" type="Endianness">
            <xsd:annotation>
                <xsd:documentation>
Endianness used in network messages
</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="IO_interface_in">
      <xsd:complexContent>
        <xsd:extension base="IO_interface_in">
        <xsd:attribute name="nbProducers" type="xsd:positiveInteger" default="1">
            <xsd:annotation>
                <xsd:documentation>
Maximum number of independent producers that may send messages to this interface.
If this value is too low communication errors may be occur.
</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="IO_operation">
      <xsd:complexContent>
        <xsd:extension base="IO_operation">
        <xsd:attribute name="bufSizeFactor" type="xsd:positiveInteger" default="1">
          <xsd:annotation>
            <xsd:documentation>
A sizing factor used to handle n times the operation. It is used in calculating the port's receive buffer
</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>


  </xsd:redefine>

</xsd:schema>
