/*
 * @file Sender.c
 * Module Interface for Module Sender
 * This file can be considered a template with the operation stubs
 * auto generated by the ECOA toolset and filled in by the module
 * developer.
 */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>

/* Include module interface header */
#include "Sender.h"

static const char* SENDER = "Sender: ";

void Sender_log_info(Sender__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, SENDER, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(SENDER, ECOA__LOG_MAXSIZE), ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    Sender_container__log_info(context, log);
}

/* Event operation handlers */
void 
Sender__tick__received (
  Sender__context* context
 )
{
  Sender_container__myEvent__send(context, 10);
}

Sender__myData_read__updated (
  Sender__context* context
 )
{

}

/* Request-Response operation handlers */

/* Lifecycle operation handlers */

void Sender__INITIALIZE__received(Sender__context* context)
{
  Sender_log_info(context, "Sender initialized!");
}

void Sender__START__received(Sender_context* context)
{
  Sender_log_info(context, "Sender started!");
}

void Sender__STOP__received(Sender_context* context)
{
  Sender_log_info(context, "Sender stopped!");
}

void Sender__SHUTDOWN__received(Sender_context* context)
{
  Sender_log_info(context, "Sender shutdown!");
}


 